### ISSUE TITLE
runprediction not working on local build

### ISSUE THREAD

**Issue by JurgenKriel** [CRBS/cdeep3m#59]
Hi, we have built a local version using docker. The training goes smoothly, but for some reason the runprediction command keeps giving the following error:

`ERROR, a non-zero exit code (127) received from PreprocessPackage.m 001 01 1fm 1
cdeep3m_1`
Any suggestions would be much appreciated.

Regards
Jurgen

**Comment by coleslaw481** [comment]
Nice work on building a Docker version. Could you share the rest of the output log for prediction?

**Comment by haberlmatt** [comment]
As per email, his error code is:
'ERROR, a non-zero exit code (127) received from PreprocessPackage.m 001 01 1fm 1' 
In the output log the following is listed:
/home/cdeep3m/preprocessworker.sh: line 110: /usr/bin/time: No such file or directory

This is on Ubuntu 18.04

We should probably remove the timing the the packaging process at this point since it's causing errors on some systems

**Comment by CrispyCrafter** [comment]
> Nice work on building a Docker version. Could you share the rest of the output log for prediction?
We updated the docker build to install "time". 

If anyone would like to contribute to the docker version here is the [repo](https://github.com/CrispyCrafter/cdeep3m-docker)

Currently it's using docker-compose entry-points to change the desired execution script.
Would love to wrap the whole cdeep3m package in a flask app to ease use and file uploads.

**Comment by haberlmatt** [comment]
That's great! I'll add a link to your docker version in our info about local install
